# syntax=docker/dockerfile:1.7-labs
FROM golang:alpine AS builder
WORKDIR /app
COPY --exclude=*docker* --exclude=/cmd/client --exclude=/cmd/web / ./
RUN go build -o ./bin/server ./cmd/server/server.go

FROM alpine
WORKDIR /app
COPY --from=builder /app/bin/server ./bin/server
EXPOSE 8080
EXPOSE 50051
CMD ["./bin/server"]