FROM golang:alpine AS builder
WORKDIR /app
COPY / ./
RUN go build -o ./bin/client ./cmd/client/client.go

FROM alpine
WORKDIR /app
COPY --from=builder /app/bin/client ./bin/client
CMD ["./bin/client"]